<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('servers')->delete();
        
        \DB::table('servers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'city_id' => 3,
                'Customer_Name' => 'admin@admin.com',
                'Server_Password' => NULL,
                'solution_location_id' => 2,
                'solution_type_id' => 23,
                'Hardware' => NULL,
                'Service_Contract' => NULL,
                'Comment' => NULL,
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => 'Yes',
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => NULL,
                'created_at' => '2021-04-01 10:02:58',
                'updated_at' => '2021-04-01 10:09:53',
                'deleted_at' => '2021-04-01 10:09:53',
                'IP' => NULL,
                'Solution_Distro' => NULL,
                'department_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'city_id' => 3,
                'Customer_Name' => 'admin@admin.com',
                'Server_Password' => NULL,
                'solution_location_id' => 2,
                'solution_type_id' => 23,
                'Hardware' => NULL,
                'Service_Contract' => NULL,
                'Comment' => NULL,
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => NULL,
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => NULL,
                'created_at' => '2021-04-01 10:04:14',
                'updated_at' => '2021-04-01 10:09:57',
                'deleted_at' => '2021-04-01 10:09:57',
                'IP' => NULL,
                'Solution_Distro' => NULL,
                'department_id' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'city_id' => 4,
                'Customer_Name' => 'Farhan Khan',
                'Server_Password' => NULL,
                'solution_location_id' => 1,
                'solution_type_id' => 1,
                'Hardware' => '192.168.144.36',
                'Service_Contract' => 'Yes',
                'Comment' => 'Changed',
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => 'Yes',
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => '1082',
                'HTTP_PORT' => '1140',
                'Webmin_PORT' => '11060',
                'created_at' => '2021-04-01 11:21:30',
                'updated_at' => '2021-04-02 12:17:31',
                'deleted_at' => NULL,
                'IP' => '192.168.11.1',
                'Solution_Distro' => 'Issabel',
                'department_id' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'city_id' => 5,
            'Customer_Name' => 'Dot36 (Trax)',
                'Server_Password' => '2SxAwIj8j7cwv0hk27CW',
                'solution_location_id' => 1,
                'solution_type_id' => 1,
                'Hardware' => '192.168.144.36',
                'Service_Contract' => NULL,
                'Comment' => 'Changed',
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => 'Yes',
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => '1082',
                'HTTP_PORT' => '1140',
                'Webmin_PORT' => '11060',
                'created_at' => NULL,
                'updated_at' => '2021-04-05 07:45:49',
                'deleted_at' => NULL,
                'IP' => '21.12.12.15',
                'Solution_Distro' => 'Issabel',
                'department_id' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'city_id' => 3,
                'Customer_Name' => 'Muhammad Umair',
                'Server_Password' => '2SxAwIj8j7cwv0hk27CW',
                'solution_location_id' => 1,
                'solution_type_id' => 1,
                'Hardware' => '192.168.144.36',
                'Service_Contract' => NULL,
                'Comment' => NULL,
                'ISD_Allowed' => 'Yes',
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => 'Yes',
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => NULL,
                'created_at' => '2021-04-01 12:24:57',
                'updated_at' => '2021-04-05 07:45:13',
                'deleted_at' => NULL,
                'IP' => '21.12.12.15',
                'Solution_Distro' => 'Nothing',
                'department_id' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'city_id' => 4,
                'Customer_Name' => 'Muhammad Umair',
                'Server_Password' => '2SxAwIj8j7cwv0hk27CW',
                'solution_location_id' => 1,
                'solution_type_id' => 4,
                'Hardware' => 'Data',
                'Service_Contract' => 'Yes',
                'Comment' => NULL,
                'ISD_Allowed' => 'Yes',
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => 'Yes',
                'Customer_Report' => 'Yes',
                'Q_Panel' => 'Yes',
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => NULL,
                'created_at' => '2021-04-01 12:26:06',
                'updated_at' => '2021-04-01 12:26:06',
                'deleted_at' => NULL,
                'IP' => '192.168.144.62',
                'Solution_Distro' => NULL,
                'department_id' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'city_id' => 3,
                'Customer_Name' => 'Muhammad Umair',
                'Server_Password' => '2SxAwIj8j7cwv0hk27CW',
                'solution_location_id' => 2,
                'solution_type_id' => 1,
                'Hardware' => NULL,
                'Service_Contract' => NULL,
                'Comment' => NULL,
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => NULL,
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => NULL,
                'created_at' => '2021-04-05 07:39:00',
                'updated_at' => '2021-04-05 07:41:12',
                'deleted_at' => NULL,
                'IP' => '10.89.189.108',
                'Solution_Distro' => NULL,
                'department_id' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'city_id' => 5,
                'Customer_Name' => 'Muhammad Umair',
                'Server_Password' => 'Ch1k6rFh+5DprE7*A91D',
                'solution_location_id' => 1,
                'solution_type_id' => 1,
                'Hardware' => 'Data',
                'Service_Contract' => 'Yes',
                'Comment' => NULL,
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => NULL,
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => '11060',
                'created_at' => '2021-04-05 07:47:40',
                'updated_at' => '2021-04-05 07:47:40',
                'deleted_at' => NULL,
                'IP' => '21.12.12.17',
                'Solution_Distro' => NULL,
                'department_id' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'city_id' => 4,
                'Customer_Name' => 'Khan Muhammad',
                'Server_Password' => 'd-s0!@+O4K&<r8bjhwx<',
                'solution_location_id' => 2,
                'solution_type_id' => 1,
                'Hardware' => NULL,
                'Service_Contract' => 'Yes',
                'Comment' => NULL,
                'ISD_Allowed' => NULL,
                'Failover_IP' => NULL,
                'Winbox' => NULL,
                'Secondary_IP' => NULL,
                'Queue_Stats' => NULL,
                'Customer_Report' => NULL,
                'Q_Panel' => NULL,
                'SSH_PORT' => NULL,
                'HTTP_PORT' => NULL,
                'Webmin_PORT' => NULL,
                'created_at' => '2021-04-06 05:47:22',
                'updated_at' => '2021-04-06 05:47:22',
                'deleted_at' => NULL,
                'IP' => '21.12.12.15',
                'Solution_Distro' => NULL,
                'department_id' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'city_id' => 5,
                'Customer_Name' => 'Ali Ahmed',
            'Server_Password' => '6bP32z)0*2>2enaoiajv',
            'solution_location_id' => 2,
            'solution_type_id' => 4,
            'Hardware' => NULL,
            'Service_Contract' => 'Yes',
            'Comment' => NULL,
            'ISD_Allowed' => NULL,
            'Failover_IP' => NULL,
            'Winbox' => NULL,
            'Secondary_IP' => NULL,
            'Queue_Stats' => NULL,
            'Customer_Report' => NULL,
            'Q_Panel' => NULL,
            'SSH_PORT' => NULL,
            'HTTP_PORT' => NULL,
            'Webmin_PORT' => NULL,
            'created_at' => '2021-04-06 05:48:25',
            'updated_at' => '2021-04-06 05:48:25',
            'deleted_at' => NULL,
            'IP' => '10.89.189.185',
            'Solution_Distro' => NULL,
            'department_id' => 1,
        ),
    ));
        
        
    }
}